replicaCount: 2
team: platform

image:
  repository: us-central1-docker.pkg.dev/dev-project-494110/devsecops-platform/product-service
  tag: "4ff513d3"

service:
  port: 8000

env: production

workloadIdentity:
  gcpServiceAccount: app-sa@dev-project-494110.iam.gserviceaccount.com

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  minReplicas: 2
  maxReplicas: 10

istio:
  inject: "true"

securityContext:
  runAsUser: 1001  # python:3.12-slim appuser UID

ingress:
  enabled: false

probes:
  liveness:
    path: /health
  readiness:
    path: /health
