replicaCount: 2
team: platform

image:
  repository: us-central1-docker.pkg.dev/YOUR_PROJECT/devsecops-platform/product-service
  tag: "latest"

service:
  port: 8000

env: production

workloadIdentity:
  gcpServiceAccount: app-sa@YOUR_PROJECT.iam.gserviceaccount.com

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  minReplicas: 2
  maxReplicas: 10

istio:
  inject: "true"
