replicaCount: 2
team: platform

image:
  repository: us-central1-docker.pkg.dev/dev-project-494110/devsecops-platform/order-service
  tag: "ccae74ff"

service:
  port: 3001

env: production

workloadIdentity:
  gcpServiceAccount: app-sa@dev-project-494110.iam.gserviceaccount.com

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  minReplicas: 2
  maxReplicas: 10

istio:
  inject: "true"

extraEnv:
  - name: USER_SERVICE_URL
    value: "http://user-service.staging.svc.cluster.local:3000"
  - name: PRODUCT_SERVICE_URL
    value: "http://product-service.staging.svc.cluster.local:8000"

ingress:
  enabled: false
