# Default values — overridden by values-staging.yaml and values-prod.yaml
replicaCount: 2
team: platform

image:
  repository: us-central1-docker.pkg.dev/dev-project-494110/devsecops-platform/user-service
  tag: "4ff513d3"

service:
  port: 3000

env: production

workloadIdentity:
  gcpServiceAccount: app-sa@dev-project-494110.iam.gserviceaccount.com

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  minReplicas: 2
  maxReplicas: 10

istio:
  inject: "true"

extraEnv:
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: jwt-secret

ingress:
  enabled: false

probes:
  liveness:
    path: /health
  readiness:
    path: /health
