replicaCount: 1
image:
  tag: "6c1e087e"

resources:
  requests:
    cpu: "30m"
    memory: "32Mi"
  limits:
    cpu: "100m"
    memory: "64Mi"

autoscaling:
  minReplicas: 1
  maxReplicas: 1

ingress:
  enabled: true
  paths:
    - path: /
